version: '3.3'
services:
  kafka-connect-exporter:
    build: .
    image: ezsolution/kafka-connect-exporter
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URI: http://192.168.1.108:8083
    tty: true